apiVersion: v1
data:
  CLUSTER_NAME: Drone
  DATABASE_URL: mysql://restricted-host:3306/mysqlrty123
  ENVIRONMENT: stage
  REGION: East US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"
kind: ConfigMap
metadata:
  name: platform-config
  namespace: stage-kaizen-app-team-hello-world-app-uat-test
